export const BURGER_LIST_REQUEST="BURGER_LIST_REQUEST"

export const BURGER_LIST_SUCCESS="BURGER_LIST_SUCCESS" 

export const BURGER_LIST_FAIL="BURGER_LIST_FAIL"
export const CREATE_BURGER_REQUEST="CREATE_BURGER_REQUEST"

export const CREATE_BURGER_SUCCESS="CREATE_BURGER_SUCCESS"

export const CREATE_BURGER_FAIL="CREATE_BURGER_FAIL"

export const UPDATE_BURGER_REQUEST="UPDATE_BURGER_REQUEST"

export const UPDATE_BURGER_SUCCESS="UPDATE_BURGER_SUCCESS"

export const UPDATE_BURGER_FAIL="UPDATE_BURGER_FAIL"

export const DELETE_BURGER_REQUEST="DELETE_BURGER_REQUEST"

export const DELETE_BURGER_SUCCESS="DELETE_BURGER_SUCCESS"

export const DELETE_BURGER_FAIL="DELETE_BURGER_FAIL"

