export const LOGIN_FAILURE="LOGIN_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"

export const LOGIN_SUCCESS="LOGIN_SUCCESS"

export const REGISTER_FAILURE="REGISTER_FAILURE"

export const REGISTER_REQUEST="REGISTER_REQUEST"

export const REGISTER_SUCCESS="REGISTER_SUCCESS"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"

export const USER_SUCCESS="USER_SUCCESS"

export const USER_FAILURE="USER_FAILURE"

export const USER_REQUEST="USER_REQUEST"

export const GET_USERS_REQUEST="GET_USERS_REQUEST"

export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"

export const GET_USERS_FAILURE="GET_USERS_FAILURE"

export const UPDATE_USER_ROLE_REQUEST="UPDATE_USER_ROLE_REQUEST"

export const UPDATE_USER_ROLE_SUCCESS="UPDATE_USER_ROLE_SUCCESS"

export const UPDATE_USER_ROLE_FAILURE="UPDATE_USER_ROLE_FAILURE"
export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"

export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"

export const DELETE_USER_FAILURE="DELETE_USER_FAILURE"